{% set name = "pymbolic" %}
{% set version = "2016.2.3" %}
{% set sha256 = "cd422e1484731421e30d3addcf0cdf9548535e6b3d006ff9cc78edde520386b6" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: {{ sha256 }}

    # Delete in the next version past 2016.2.3.
    patches:
    - geo-alg-integrality-test.patch

build:
    number: 1
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
        - pytools
        - six
    run:
        - python
        - numpy
        - pytools
        - six

test:
    requires:
        - pytest
    imports:
        - {{ name }}
    commands:
         - cd $SRC_DIR/test && python -m pytest  # [unix]
         - cd %SRC_DIR%/test && python -m pytest  # [win]

about:
    home: http://pypi.python.org/pypi/{{ name }}
    dev_url: http://github.com/inducer/{{ name }}
    doc_url: https://documen.tician.de/{{ name }}
    license: MIT
    license_file: LICENSE
    summary: A package for symbolic computation

extra:
    recipe-maintainers:
        - inducer
